export { default as main } from './main.web'
export { default as about } from './about.web'
export { default as tech } from './tech.web'
export { default as blog } from './blog.web'
export { default as why } from './why.web'
export { default as vote } from './vote.web'
export { default as privacy } from './privacy.web'
